In [1]:
import numpy as np

In [12]:
mat1D = np.array([1,2,3,4,5,6,7,8,9,10])
mat2D = np.array([[1,2,3],[4,6,7],[8,9,10]])

In [13]:
print(mat1D)
print(mat2D)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3]
 [ 4  6  7]
 [ 8  9 10]]


In [18]:
print(mat1D[0])

print(mat2D[0])
print(mat2D[1])
print(mat2D[2])

print(mat2D[1] [2])

1
[1 2 3]
[4 6 7]
[ 8  9 10]
7


In [16]:
print(mat1D + 5)

print(mat2D + 10)

[ 6  7  8  9 10 11 12 13 14 15]
[[11 12 13]
 [14 16 17]
 [18 19 20]]


In [20]:
print(mat1D.shape)
print(mat2D.shape)

(10,)
(3, 3)


In [21]:
print(mat1D.size)
print(mat2D.size)

10
9


In [49]:
#special matrix
mZero = np.zeros((3,3))
mIdentity = np.eye((4))
mFull = np.full((4,4),7)
mOne = np.ones((5,4))
mRandomFloat = np.random.rand(5,5)
mRandomInt = np.random.randint(10,101, size = 9)

In [32]:
print(mZero)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [34]:
print(mIdentity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [35]:
print(mFull)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [37]:
print(mOne)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [53]:
print(mRandomFloat)

[[0.2457378  0.66099238 0.49909823 0.84110493 0.66265425]
 [0.83798555 0.88709805 0.01069593 0.74299264 0.66269225]
 [0.92687218 0.07090517 0.02829833 0.55398408 0.61409887]
 [0.87343366 0.71213028 0.03668332 0.16983054 0.04415226]
 [0.48302534 0.05499949 0.54421099 0.54408425 0.03196469]]


In [50]:
print(mRandomInt)

[89 57 75 34 55 41 48 32 17]


In [75]:
x = np.array([2,6,9,1,5,3])
y = np.array([2,6,1,7,3,4])

dotProduct = np.dot(x,y)
addMat = np.add(x,y)
minValue = np.min(x)
maxValue = np.max(y)
meanValue = np.mean(y)
medianValue = np.median(y)
stdValue = np.std(y)

print(f"Hasil dari dot product: {dotProduct}")
print(f"Hasil dari penjumlahan matriks: {addMat}")
print(f"Nilai terkecil dari matriks {x}: {minValue}")
print(f"Nilai terbesar dari matrriks {y}: {maxValue}")
print(f"Nilai rata-rata dari matrriks {y}: {meanValue}")
print(f"Nilai tengah dari matriks {y}: {medianValue}")
print(f"Nilai deviasi dari {y}: {stdValue}")

Hasil dari dot product: 83
Hasil dari penjumlahan matriks: [ 4 12 10  8  8  7]
Nilai terkecil dari matriks [2 6 9 1 5 3]: 1
Nilai terbesar dari matrriks [2 6 1 7 3 4]: 7
Nilai rata-rata dari matrriks [2 6 1 7 3 4]: 3.8333333333333335
Nilai tengah dari matriks [2 6 1 7 3 4]: 3.5
Nilai deviasi dari [2 6 1 7 3 4]: 2.1147629234082532


In [74]:
myArray = np.array([[1,2,3],[4,5,6]])

reshape = myArray.reshape(3,2)
flatten = myArray.flatten()

print(reshape)
print(flatten)

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [78]:
#filtering
nilaiSiswa = np.array([80,90,50,70,80,85,100,55,95])
lulus = nilaiSiswa[nilaiSiswa > 50]
jumlah = lulus.size
print(lulus)
print(jumlah)

[ 80  90  70  80  85 100  55  95]
8
